### ISSUE TITLE
Fieldtype(s)

### ISSUE THREAD

**Issue by cole007** [nystudio107/generator-craftplugin#10]
Couple of issues/questions:
1. should the generator assume creating a model when model is deselected for creating a fieldtype (e.g. if which wish to default to the standard/generic content table)
2. can the `prepValueFromPost()` and `prepValue()` methods in the generated `fieldType.php` return a default value (`return value`). otherwise will clear out the values saved/returned

Ta

**Comment by khalwat** [comment]
Yeah I wasn't sure how to handle it, so it assumes you want a model (which in most cases, I think is correct).

I've fixed the `return $value` issue, thanks!
