### ISSUE TITLE
Foreach error on route /amseed/generators/new

### ISSUE THREAD

**Issue by atillay** [nystudio107/generator-craftplugin#15]
Hi, first thanks for this plugin.
Unfortunately when I hit the "New dummy generator" button I get an error on the following page (/amseed/generators/new). You'll see the details on the attached screenshot. My PHP version is 7.0.2.
![screencapture-localhost-bravoure-bravoure-craft-public-admin-amseed-generators-new-1475654192421](https://cloud.githubusercontent.com/assets/9945218/19105615/33babd8a-8ae3-11e6-8ba2-ef33bbc6601e.png)

**Comment by khalwat** [comment]
I think you posted this in the wrong place...

**Comment by atillay** [comment]
My bad ! Sorry for this..
