### ISSUE TITLE
&'s getting encoded in composer.json

### ISSUE THREAD

**Issue by brandonkelly** [nystudio107/generator-craftplugin#18]
If your author name has an `&` (e.g. `Pixel & Tonic`) it will get encoded in the generated composer.json:

```json
"name": "Pixel &amp; Tonic",
```

**Comment by khalwat** [comment]
Looks like by default, EJS escapes html entities:

http://stackoverflow.com/questions/25177035/passing-html-tags-as-ejs-variables-value

**Comment by khalwat** [comment]
Fixed in 1.2.8: https://github.com/nystudio107/generator-craftplugin/releases/tag/1.2.8

Turns out you just use `<%-` instead of `<%=` to output unescaped values

Live now on https://pluginfactory.io/
