### ISSUE TITLE
Package names should be kebab-case

### ISSUE THREAD

**Issue by brandonkelly** [nystudio107/generator-craftplugin#20]
The generated package name in composer.json should be a kebab-case'd version of the plugin name. Right now it's just all-lowercase without any spaces:

```json
"name": "craftcms/elementapi",
```

should be:

```json
"name": "craftcms/element-api",
```

(This is a matter of preference, but the convention among other Composer packages seems to be kebab-case.)

**Comment by khalwat** [comment]
hmmmm. Does this apply to the namespacing globally as well?  e.g.: 

```
namespace craftcms/element-api;
```

vs.

```
namespace craftcms/elementapi;
```

Right now, it does the latter everywhere.

**Comment by brandonkelly** [comment]
Nope namespace should be lowercase w/out any spaces/hyphens/etc. This issue only affects package names.

**Comment by khalwat** [comment]
All set:

## 1.2.11 - 2017.02.14
### Changed
* Composer package names and github-related names are now in kebab-case
