### ISSUE TITLE
`extra.developer` and `extra.developerUrl` are redundant if the info is already in `authors`

### ISSUE THREAD

**Issue by brandonkelly** [nystudio107/generator-craftplugin#21]
There's no need to specify the developer name/URL in both `extra.developer`/`extra.developerUrl` **and** the `authors` array. Maybe just pick one? (The `authors` array is probably preferable.)

**Comment by khalwat** [comment]
Same with the version, I assume?

**Comment by khalwat** [comment]
As long as Craft is looking in both places, I'm all for getting rid of the redundant info in `extra.`

**Comment by khalwat** [comment]
Fixed in 1.2.7: https://github.com/nystudio107/generator-craftplugin/releases/tag/1.2.7

Live on https://pluginfactory.io/
