### ISSUE TITLE
`extra.description` is redundant if the info is already in `description`

### ISSUE THREAD

**Issue by brandonkelly** [nystudio107/generator-craftplugin#22]
There's no need to specify the description in both `extra.description` **and** the top-level `description` property. Maybe just pick one? (The top-level `description` property is probably preferable.)

**Comment by khalwat** [comment]
So Craft will look for it in both places? Easy.

**Comment by khalwat** [comment]
Fixed in 1.2.7: https://github.com/nystudio107/generator-craftplugin/releases/tag/1.2.7

Live on https://pluginfactory.io/
