### ISSUE TITLE
Bad casing on i8n category name

### ISSUE THREAD

**Issue by stefan-h-singer** [nystudio107/generator-craftplugin#24]
In my case, t('wmylForms', ...) was used when it should be all lowercase.

**Comment by stefan-h-singer** [comment]
This is when creating a widget for the plugin.

**Comment by khalwat** [comment]
## 1.2.24 - 2017.03.14
### Fixed
* Changed the translation category `toLowerCase()` for compliance with Craft `3.0.0-beta-7`
