### ISSUE TITLE
Settings page gets twig error (Craft 3)

### ISSUE THREAD

**Issue by owldesign** [nystudio107/generator-craftplugin#27]
Craft 3 generator. `someField` doesn't exist in the Settings model.

Basically `$someAttribute` needs to be renamed to `$someField` as well as updated in the `rules()` method..

Settings services already has it set as `someField` so that's good.

Thanks.

**Comment by khalwat** [comment]
Fixed in 1.2.36:

* Renamed `someField` -> `someAttribute` to fix Twig errors on the plugin Settings page
