### ISSUE TITLE
Author URL

### ISSUE THREAD

**Issue by fractorr** [nystudio107/generator-craftplugin#28]
First off this generator is AWESOME!!!!!!!!

I came across a minor issue with the Author URL.  If you just put in domain.com and leave out the http:// or https:// when you publish it to packagist they complain that it is not a valid domain.

Easy enough for me to make that quick update in the generated code but just thought I would let you know, maybe add a tooltip to it.

**Comment by khalwat** [comment]
yeah I probably should add a default protocol is none is present (as well as instructions in a tooltip)
