### ISSUE TITLE
Project Root thrown off by .yo-rc.json

### ISSUE THREAD

**Issue by brianjhanson** [nystudio107/generator-craftplugin#30]
When trying to run:
```
yo craftplugin --pluginComponents="twigextensions"
```

It tries to generate a new plugin because I have a `.yo-rc.json` file in a parent directory. This file causes `yo` to set the project root to that parent directory rather than running the generator in the current directory.

**Comment by khalwat** [comment]
hmmmm. I'm not sure how this would/should be addressed? Suggestions?

**Comment by brianjhanson** [comment]
I'm not really sure, I solved it by running `rm ~/.yo-rc.json` to delete the file, but that doesn't seem like a super long term fix.

It looks like [Yeoman has an issue for the same problem](https://github.com/yeoman/yeoman/issues/635), [as does yo](https://github.com/yeoman/yo/issues/204), but deleting the file was the only solution there as well. 

Either way, likely not a widespread issue, and at least now this issue is here to help point people towards a fix.

**Comment by khalwat** [comment]
Fair 'nuff!
