### ISSUE TITLE
Craft 3 Beta 20 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [nystudio107/generator-craftplugin#32]
The following changes should be made so plugins are compatible with [Beta 20](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#300-beta20---2017-07-07-critical):

(Examples assume a plugin name of `Foo Bar`.)

- [x] `extra.handle` in composer.json should be `"foo-bar"` instead of `"fooBar"`
- [x] src/translations/en/foobar.php should be renamed to `foo-bar.php`
- [x] `Craft::t()` calls should pass `'foo-bar'` as the first argument instead of `'foobar'`
- [x] the `|t` filters in the generated template(s) should be `|t('foo-bar')` (these are incorrectly not passing any category currently, meaning that they will default to the `site` category)
- [x] `defineTemplateComponent()` should be replaced with a listener for the `defineComponents` event on `craft\web\twig\variables\CraftVariable`
- [x] Installation instructions in the readme should only cover Composer installs (Beta 20 dropped support for manual plugin installs)

**Comment by brandonkelly** [comment]
(Taking a first pass at this…)

**Comment by khalwat** [comment]
Thanks Brandon, I merged the PRs, and will look into the translations now, and then do some testing and a release.

**Comment by khalwat** [comment]
Okay I fixed the kebab-case translation files. BTW there is a `develop` branch now if you have other PRs

**Comment by brandonkelly** [comment]
Sweet thanks!
