### ISSUE TITLE
Create CP Nav

### ISSUE THREAD

**Issue by mcmadafly** [nystudio107/generator-craftplugin#35]
Still scratching my head on this. I took a look at the [Redirect](https://github.com/Dolphiq/craft3-plugin-redirect) Plugin and I thought it was as simple as 

`
use craft\events\RegisterCpNavItemsEvent;
`
and
`
public function getCpNavItem()
    {
        return [
        'url'=> 'newsblast',
        'label'=>Craft::t('newsblast', 'Newsblast'),
        'icon' => 'icon'
      ];
    }
`
but Brandon says you have to run this through a cache event? https://github.com/craftcms/cms/issues/1838

Could the generator include an option for a control panel nav item?

**Comment by johnfmorton** [comment]
Hello Adam. Please get in touch with me. You've got my contact info.

**Comment by khalwat** [comment]
I think maybe @brandonkelly copied the wrong code sample, it should be: 

```
// New:
use craft\events\RegisterCpNavItemsEvent;
use craft\web\twig\variables\Cp;
use yii\base\Event;

Event::on(Cp::class, Cp::EVENT_REGISTER_CP_NAV_ITEMS, function(RegisterCpNavItemsEvent $event) {
    if (\Craft::$app->user->identity->admin) {
        $event->navItems['foo'] = [
            'label' => \Craft::t('myplugin', 'Utils'),
            'url' => 'utils'
        ];
    }
});
```
