### ISSUE TITLE
Generate without code comments not working

### ISSUE THREAD

**Issue by svenjungnickel** [nystudio107/generator-craftplugin#40]
When I unselect the code comment option on the command line tool, the generator generates code comments regardless. At the online service on https://pluginfactory.io/ it is working fine.
Maybe I'm using the command line tool wrong? 

I'm using the latest generator version 1.3.7 as well the latest yeoman version 2.0.

**Comment by khalwat** [comment]
Perhaps you can try Yeoman 1.8.5? I have not tested anything with Yeoman 2.0 yet.

**Comment by svenjungnickel** [comment]
I tested it with Yeoman 1.8.5. now but it is still not working.

**Comment by khalwat** [comment]
Paste in the command line arguments you're using, please?

**Comment by svenjungnickel** [comment]
I used `yo craftplugin` without any parameters and filled in my details. At the question about the code comments I unselect the option.

I just tested it with the parameter `yo craftplugin --codeComments=""` and this is working. Its just not working if you provide no parameters.

**Comment by khalwat** [comment]
Weird, it must be something with `optionOrPrompt`. Which API version do you select? 2.5.x or 3.x?

**Comment by svenjungnickel** [comment]
I select 3.x. I didn’t test it with 2.5.x yet.

**Comment by khalwat** [comment]
Alright I'll give it a whirl, thanks

**Comment by khalwat** [comment]
This has been fixed in 1.3.8:

https://github.com/nystudio107/generator-craftplugin/releases/tag/1.3.8

...and has been deployed to https://pluginfactory.io/
