### ISSUE TITLE
Leaving Fieldtype input blank leads to ".php" file being written

### ISSUE THREAD

**Issue by mildlygeeky** [nystudio107/generator-craftplugin#44]
Subject pretty much says it all — Craft 3.x, enabled "Fieldtype" but left the input blank, and it wrote a ".php" filename and the PHP class didn't have a name.

**Comment by mildlygeeky** [comment]
Other issues as well — asset bundle files are saved as ".css", ".js", etc.

**Comment by khalwat** [comment]
Fixed in 1.3.13:

https://github.com/nystudio107/generator-craftplugin/releases/tag/1.3.13

**Comment by chasegiunta** [comment]
This seems to be happening leaving ElementTypes input blank as well.
