### ISSUE TITLE
Craft 3 module generator zip file is empty

### ISSUE THREAD

**Issue by marionnewlevant** [nystudio107/generator-craftplugin#45]
Generated zip file has only .craftplugin file. This one is named `site` and has Service, Twig Extension, Variables, with comments turned on.
[sitemodule.zip](https://github.com/nystudio107/generator-craftplugin/files/1658034/sitemodule.zip)

**Comment by boscho87** [comment]
:+1: 
when "CodeCommnts" activated, but only for Craft 3 Modules

**Comment by khalwat** [comment]
So this *might* have been fixed in 1.4.1; I'm unable to reproduce it locally, either via the command line or via the website.

https://github.com/nystudio107/generator-craftplugin/releases/tag/1.4.1

**Comment by khalwat** [comment]
Is this still happening for anyone @marionnewlevant @boscho87 ?

**Comment by boscho87** [comment]
Seems fixed will check tomorrow

**Comment by boscho87** [comment]
😅👍🏾
