### ISSUE TITLE
Wrong namespace in the Controller Classes [Craft3 Modules]

### ISSUE THREAD

**Issue by boscho87** [nystudio107/generator-craftplugin#47]
When generating Craft3 Modules the namespace in the main Module file `$this->controllerNamespace` and in the Controllers are wrong...

in my case it was:
```php
$this->controllerNamespace = 'donatemodule\controllers'; //wrong
$this->controllerNamespace = 'modules\donatemodule\controllers'; //right

// and:
namespace donatemodule\controllers; //wrong
namespace modules\donatemodule\controllers; //right
```

**Comment by khalwat** [comment]
Fixed in 1.4.1:

https://github.com/nystudio107/generator-craftplugin/releases/tag/1.4.1
