### ISSUE TITLE
Wrong basePath in the Module Class [Craft3 Modules] 

### ISSUE THREAD

**Issue by boscho87** [nystudio107/generator-craftplugin#48]
in the main Module file the the base path in the Contructor is wrong:

in my case:

``` php
'basePath' => '@donatemodule/translations', //wrong
'basePath' => '@modules/donatemodule/translations', // right

**Comment by khalwat** [comment]
Fixed in 1.4.1:

https://github.com/nystudio107/generator-craftplugin/releases/tag/1.4.1
