### ISSUE TITLE
Wrong File names for Generated Classes [Craft 3 Modules]

### ISSUE THREAD

**Issue by boscho87** [nystudio107/generator-craftplugin#49]
I left the name of the widget class and the name of the services class empty. Now in my services dir and in my widgets dir, i have a file named `.php` instead of `{DefaultService}.php` and `{DefaultWidget}.php`

**Comment by khalwat** [comment]
Fixed in 1.4.1:

https://github.com/nystudio107/generator-craftplugin/releases/tag/1.4.1
