### ISSUE TITLE
widget iconPath() incorrect (craft3 module)

### ISSUE THREAD

**Issue by anchovy** [nystudio107/generator-craftplugin#54]
HI

Craft CMS 3.0.3.1 (PRO)

When creating a Craft 3 module with widgets - the iconPath in the widget is missing the prefix 'modules', as the alias is set in /modules/{module_name/src/{module_name}.php  __construct() as:

`Craft::setAlias('@modules/restmodule', $this->getBasePath());`

The function iconPath() /modules/{module_name}/src/widgets/{widget_name).php is:
` return Craft::getAlias("@{module_name}/assetbundles/fibrewidget/dist/img/{widget_name}-icon.svg");`

when it should be:
` return Craft::getAlias("@modules/{module_name}/assetbundles/fibrewidget/dist/img/{widget_name}-icon.svg");`

**Comment by khalwat** [comment]
Thanks, I'll get this fixed up.

**Comment by MattWilcox** [comment]
Same error here in October, but a simple fix - thanks both!

**Comment by bymayo** [comment]
As well as fixing it in `/modules/{module_name}/src/{module_name}.php` I also had to change `iconUrl` variable in `/modules/{module_name}/src/templates/_components/widgets/{module_name}_body.php` from `@{module_name}` to `@modules/{module_name}`

**Comment by TomDeSmet** [comment]
Just had this same issue. Would be nice if this could be fixed in the pluginfactory :)
Thanks for the solution guys!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/generator-craftplugin/commit/00702811417fa47b7866858ed634480676dd0272
