### ISSUE TITLE
Include all built-in fields in settings example

### ISSUE THREAD

**Issue by sjelfull** [nystudio107/generator-craftplugin#6]
Would be great if you could add 1 example of each built-in field to the settings example.

**Comment by khalwat** [comment]
I've wanted to do this, but I think I'm going to wait until Craft 3 to try to do it; because they very well may change the format on me.

**Comment by khalwat** [comment]
I'm probably not going to do this... at least not for the 2.5.x API.  I'll definitely keep it in mind when the 3.0.x API gets solidified, and I implement it on pluginfactory.io tho.

**Comment by sjelfull** [comment]
Cool. I'll send you a pull request if I ever get too bothered about this and add them myself.
