### ISSUE TITLE
Unable to create plugin with default controller and named controller

### ISSUE THREAD

**Issue by Ozogu** [nystudio107/generator-craftplugin#64]
Internal Server Error
RecursiveDirectoryIterator::__construct(/home/forge/pluginfactory.io/craft/storage/runtime/temp/pluginfactory/asdads): failed to open dir: No such file or directory

Steps to reproduce:

1. Enable controller radio box (or I suspect anything)
2. Give handle name
3. Add blank (for default)
![image](https://user-images.githubusercontent.com/16854835/42984542-b3335a30-8bf5-11e8-832c-f31172093ce8.png)
4. submit

**Comment by khalwat** [comment]
This is due to having an underscore in the plugin name/handle: https://github.com/nystudio107/generator-craftplugin/issues/75
