### ISSUE TITLE
CLI: Generate files in subdirectories

### ISSUE THREAD

**Issue by timeverts** [nystudio107/generator-craftplugin#80]
This is a feature request.

It would be great if it were possible to have the CLI generate template files in subdirectories.

For example, `yo craftplugin --pluginComponents="services" --serviceName="foo/bar"` would generate the service file at `services/foo/Bar.php` with the correct namespace of the subdirectory inserted as well. In the current implementation, this command generates the file `services/Foobar.php`, which is not what is desired.

If using `/` is too generic for indicating subdirectories, then alternatively `\` could be used as the directory seperator instead.

**Comment by khalwat** [comment]
I don't think this type of path/namespace handling is going to be implemented, unless you wish to PR it in. That's always welcome!
