### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cruiser12** [nystudio107/generator-craftplugin#81]
Hi,

when adding routes to Module class, we should remove "modules" from the path and start with the module name.

![image](https://user-images.githubusercontent.com/133954/52570600-0e8f3280-2e14-11e9-8e75-b6816c7fa11f.png)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/generator-craftplugin/commit/0c2caeea5739055d86907535878492b4cab4dcfa
