### ISSUE TITLE
Unnecessary required fields (for a module)

### ISSUE THREAD

**Issue by lindseydiloreto** [nystudio107/generator-craftplugin#83]
When generating a module, these fields are not necessary (and don't do anything)...

<img width="750" alt="Ω 2019-05-16 at 2 57 50 PM" src="https://user-images.githubusercontent.com/5309692/57890244-ed135d80-77eb-11e9-8c8c-53b0c54bb07f.png">

**Comment by lindseydiloreto** [comment]
Ah, I do see where they're getting used (in the docblocks). I'm still not sure they need to be required.

**Comment by khalwat** [comment]
They are used in the docblocks -- I think it's probably fine they are required
