### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by cole007** [nystudio107/generator-craftplugin#9]
Not sure if it is possible but when use the generator at https://pluginfactory.io/ always saves with the wrong permissions so when save into my project the addon is not detected (in Settings > Plugin).

**Comment by khalwat** [comment]
Wrong permissions in terms of...?  The owner?  The group?

**Comment by cole007** [comment]
Whenever I save output and move into plugins folder it can't see it initially (in Settings > Plugins). 
I have to manually change the permissions to see it.

-- 
Cole Henley 
Technical Director 
Mud // Clear Digital Thinking 

3a Fountain Buildings Bath BA1 5DU 
01225 471 465 

On 28 April 2016 at 14:50:47, khalwat (notifications@github.com) wrote:

Wrong permissions in terms of...? The owner? The group?

**Comment by khalwat** [comment]
Okay, but what are the permissions before you change them?  And what do you have to change them to?

**Comment by cole007** [comment]
Whatever works ;)

If I look at a generated plugin I get permissions `rwx --- ---` (700).
However if I look at other downloaded Craft plugins these are usually `rwx r-x r-x` (755) so guessing if can be generated with read and execute permissions for Group and World users that would work

**Comment by khalwat** [comment]
I'm looking at the actual thing that is generated on the server, and the permissions are `755`:

```
drwxr-xr-x   5 nginx nginx 4096 Apr 28 03:01 recipe
```

Perhaps the folder you are downloading and extracting the zip file into on your computer has the permissions set to `700`?

**Comment by cole007** [comment]
Okay, thanks. File under problem between user and keyboard!
