### ISSUE TITLE
twig extension classes are deprecated

### ISSUE THREAD

**Issue by keyurshah** [nystudio107/generator-craftplugin#90]
Hello,

It looks as of twig 2.7, that Twig_Extension is deprecated according to phpstorm.

In researching the issue, it recommended replacing 

` \Twig_Extension` with `\Twig\Abstract\Extension`

`Twig_SimpleFilter` with `\Twig\TwigFilter`

`Twig_SimpleFunction` with `Twig\TwigFunction`

https://twig.symfony.com/doc/2.x/deprecated.html

let me know if I should make a pull request. Thanks

thanks.

**Comment by khalwat** [comment]
It would be FANTASTIC if you could do a pull request for this @keyurshah

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/generator-craftplugin/commit/a90cb8279cec99b243dca377e3facb62c669ef7b

**Comment by keyurshah** [comment]
Thanks! Sorry could not get to it. About to launch our commerce store this week hopefully!
